# Generated by Django 5.1.3 on 2024-11-13 13:34

import django.db.models.deletion
import football_team_manager.players.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[football_team_manager.players.validators.validate_player_age])),
                ('price', models.BigIntegerField()),
                ('image_url', models.URLField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.team')),
            ],
        ),
    ]
