# Generated by Django 5.1.3 on 2024-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('gk', 'Goalkeeper'), ('rb', 'Right Back'), ('lb', 'Left Back'), ('cb', 'Central Back'), ('cdm', 'Defensive Midfielder'), ('cm', 'Central Midfielder'), ('lm', 'Left Midfielder'), ('rm', 'Right Midfielder'), ('lw', 'Left Winger'), ('rw', 'Right Winger'), ('st', 'Striker')], default=1),
            preserve_default=False,
        ),
    ]
