# Generated by Django 5.1.3 on 2024-11-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image_url',
        ),
        migrations.AddField(
            model_name='player',
            name='image_photo',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
