# Generated by Django 5.1.3 on 2024-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('4-3-3', '4-3-3'), ('3-4-3', '3-4-3'), ('3-5-2', '3-5-2'), ('4-4-2', '4-4-2')])),
            ],
        ),
    ]
