# Generated by Django 5.1.3 on 2024-11-13 13:34

import django.db.models.deletion
import football_team_manager.teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True, validators=[football_team_manager.teams.validators.validate_team_name])),
                ('players', models.IntegerField(validators=[football_team_manager.teams.validators.validate_team_players])),
                ('team_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.league')),
            ],
        ),
    ]
