# Generated by Django 5.1.3 on 2024-11-20 18:21

import football_team_manager.teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, validators=[football_team_manager.teams.validators.validate_team_name]),
        ),
    ]
