# Generated by Django 5.1.3 on 2024-11-13 13:34

import football_team_manager.leagues.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=200, validators=[football_team_manager.leagues.validators.validate_league_name])),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
